# common words to replace in questions (without safewords)
commonwords = ['the', 'I', 'to', 'a', 'of',
               'and', 'is', 'in', 'with',
               'that', 'this', 'have', 'why',
               'for', 'it', 'but', 'an',
               'be', 'as', 'like', 'do', 'can',
               'my', 'am', 'want', 'from', 'not', 'on',
               'would', 'The', 'are', 'data',
               'way', 'there', "I'm", 'get',
               'How', 'which', 'values', 'each',
               'code', 'if', 'how', 'by', 'or',
               'use', 'so', 'all', 'some', 'one',
               'into', 'following', 'trying', 'two',
               'list', 'what', 'need', 'arrays', 'Is',
               'value', 'when', 'This', 'Python', 'column',
               'python', 'same', 'has', 'at', 'first', '=',
               'then', 'any', 'where', 'me', 'tried',
               'should', 'i', 'file', 'only', 'know',
               'find', 'will', 'you', 'just', 'But',
               'For', 'What', 'was', 'error', 'something',
               'row', 'number', 'So', 'more', 'x', 'out',
               'new', 'this:', 'elements', 'My', "I've",
               'than', 'could', 'In', 'different', 'does',
               'other', 'columns', 'example', 'output', '-',
               'problem', 'rows', 'image', '1', 'make', 'also',
               '2', "don't", 'up', 'these', 'very', 'array.',
               'time', 'result', 'doing', 'between', 'If',
               'plot', 'set', '2D', 'It', 'shape', 'convert',
               'However,', 'without', 'Any', 'question',
               'about', 'work', 'help', 'them', 'over',
               'Here', 'line', 'loop', 'seems', 'A', 'another',
               '3', 'because', 'this?', 'no', '0', 'pandas',
               ':', 'such', 'read', 'And', "can't", 'given',
               'size', 'looks', "I'd", "doesn't", 'works',
               'second', 'every', 'large', 'Thanks',
               'solution', 'simple', 'points', 'run',
               'able', 'return', 'try', 'indices',
               'possible', 'gives', 'through', 'above',
               'code:', 'getting', 'see', 'method', "it's"]